[project]
name = "pyjaapp-backend"
version = "0.1.0"
description = "Serverless FastAPI with DynamoDB, S3, Cognito"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "mangum",
    "boto3",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "uvicorn",
    "sqlalchemy>=2.0.48",
    "asyncpg>=0.31.0",
    "alembic>=1.18.4",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt==4.0.1",
    "pyjwt>=2.12.1",
    "google-auth>=2.49.1",
    "requests>=2.33.0",
    "email-validator>=2.3.0",
    "resend>=2.26.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    "pytest-asyncio",
    "pre-commit",
    "black",
    "isort",
    "flake8"
]
